version: '3.8'

volumes:
  db_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    container_name: foodgram-front
    image: lifeisastruggle64/foodgram_frontend
    command: cp -r /app/build/. /static
    volumes:
      - static:/static/
  backend:
    container_name: foodgram-back
    image: lifeisastruggle64/foodgram_backend
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - db
  gateway:
    container_name: foodgram-proxy
    image: lifeisastruggle64/foodgram_gateway
    ports:
      - 8080:80
    volumes:
      - static:/static/
      - media:/mediafiles/
