# Generated by Django 3.2.16 on 2024-07-19 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_coocking_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Amount не может быть меньше 1')], verbose_name='Количество'),
        ),
    ]
