# Generated by Django 3.2.16 on 2024-07-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240720_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='times_favorited',
            field=models.IntegerField(blank=True, default=0, verbose_name='Добавлен в избранное'),
        ),
    ]
