# Generated by Django 3.2.16 on 2024-07-06 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='is_favorited_by', to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_list',
            field=models.ManyToManyField(related_name='in_shopping_list_of', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
    ]
