# Generated by Django 3.2.16 on 2024-07-09 12:37

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240706_1224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.FoodgramUserManager()),
            ],
        ),
    ]
